In [1]:
# import basic stuff
import sklearn
import pandas as pd
import numpy as np
import itertools
from tqdm import tqdm

# import tensorflow and keras stuff
!pip install tensorflow_probability
import tensorflow_probability as tfp
import tensorflow as tf

tfd = tfp.distributions
from keras.layers import *
from keras.models import *
from keras.callbacks import *
from keras.optimizers import *
from keras.losses import *
from keras.regularizers import *
import keras.backend as K

# import kflod stuff
from sklearn.model_selection import KFold

# import preprocessing functions
from sklearn.model_selection import StratifiedShuffleSplit
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import FunctionTransformer, StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.metrics import mean_squared_error

# import comparison models
from xgboost import XGBClassifier, XGBRegressor


!pip install interpret
from interpret.glassbox import (
    ExplainableBoostingClassifier,
    ExplainableBoostingRegressor,
)



# plotting
import matplotlib.pyplot as plt


from scipy.stats import entropy, wasserstein_distance

!pip install properscoring
import properscoring as ps

Requirement already satisfied: tensorflow_probability in /usr/local/lib/python3.10/dist-packages (0.20.1)
Requirement already satisfied: absl-py in /usr/local/lib/python3.10/dist-packages (from tensorflow_probability) (1.4.0)
Requirement already satisfied: six>=1.10.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow_probability) (1.16.0)
Requirement already satisfied: numpy>=1.13.3 in /usr/local/lib/python3.10/dist-packages (from tensorflow_probability) (1.22.4)
Requirement already satisfied: decorator in /usr/local/lib/python3.10/dist-packages (from tensorflow_probability) (4.4.2)
Requirement already satisfied: cloudpickle>=1.3 in /usr/local/lib/python3.10/dist-packages (from tensorflow_probability) (2.2.1)
Requirement already satisfied: gast>=0.3.2 in /usr/local/lib/python3.10/dist-packages (from tensorflow_probability) (0.4.0)
Requirement already satisfied: dm-tree in /usr/local/lib/python3.10/dist-packages (from tensorflow_probability) (0.1.8)
Collecting interpret
  Downloading interpret-0.4.3-py3-none-any.whl (1.4 kB)
Collecting interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3 (from interpret)
  Downloading interpret_core-0.4.3-py3-none-any.whl (16.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.9/16.9 MB 49.8 MB/s eta 0:00:00
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.10/dist-packages (from interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3->interpret) (1.3.1)
Requirement already satisfied: numpy>=1.11.1 in /usr/local/lib/python3.10/dist-packages (from interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3->interpret) (1.22.4)
Requirement already satisfied: scipy>=0.18.1 in /usr/local/lib/python3.10/dist-packages (from interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3->interpret) (1.10.1)
Requirement already satisfied: pandas>=0.19.2 in /usr/local/lib/python3.10/dist-packages (from interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3->interpret) (1.5.3)
Requirement already satisfied: scikit-learn>=0.18.1 in /usr/local/lib/python3.10/dist-packages (from interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3->interpret) (1.2.2)
Collecting shap>=0.28.5 (from interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3->interpret)
  Downloading shap-0.42.1-cp310-cp310-manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (547 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 547.9/547.9 kB 52.8 MB/s eta 0:00:00
Collecting dill>=0.2.5 (from interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3->interpret)
  Downloading dill-0.3.7-py3-none-any.whl (115 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 115.3/115.3 kB 16.3 MB/s eta 0:00:00
Requirement already satisfied: psutil>=5.6.2 in /usr/local/lib/python3.10/dist-packages (from interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3->interpret) (5.9.5)
Collecting SALib>=1.3.3 (from interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3->interpret)
  Downloading salib-1.4.7-py3-none-any.whl (757 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 758.0/758.0 kB 61.9 MB/s eta 0:00:00
Requirement already satisfied: ipykernel>=4.10.0 in /usr/local/lib/python3.10/dist-packages (from interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3->interpret) (5.5.6)
Requirement already satisfied: ipython>=5.5.0 in /usr/local/lib/python3.10/dist-packages (from interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3->interpret) (7.34.0)
Requirement already satisfied: plotly>=3.8.1 in /usr/local/lib/python3.10/dist-packages (from interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3->interpret) (5.13.1)
Collecting skope-rules>=1.0.1 (from interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3->interpret)
  Downloading skope_rules-1.0.1-py3-none-any.whl (14 kB)
Collecting lime>=0.1.1.33 (from interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3->interpret)
  Downloading lime-0.2.0.1.tar.gz (275 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 275.7/275.7 kB 33.2 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting dash>=1.0.0 (from interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3->interpret)
  Downloading dash-2.11.1-py3-none-any.whl (10.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.4/10.4 MB 95.1 MB/s eta 0:00:00
Collecting dash-core-components>=1.0.0 (from interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3->interpret)
  Downloading dash_core_components-2.0.0-py3-none-any.whl (3.8 kB)
Collecting dash-html-components>=1.0.0 (from interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3->interpret)
  Downloading dash_html_components-2.0.0-py3-none-any.whl (4.1 kB)
Collecting dash-table>=4.1.0 (from interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3->interpret)
  Downloading dash_table-5.0.0-py3-none-any.whl (3.9 kB)
Collecting dash-cytoscape>=0.1.1 (from interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3->interpret)
  Downloading dash_cytoscape-0.3.0-py3-none-any.whl (3.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 109.9 MB/s eta 0:00:00
Collecting gevent>=1.3.6 (from interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3->interpret)
  Downloading gevent-23.7.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (6.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.4/6.4 MB 124.1 MB/s eta 0:00:00
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.10/dist-packages (from interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3->interpret) (2.27.1)
Collecting treeinterpreter>=0.2.2 (from interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3->interpret)
  Downloading treeinterpreter-0.2.3-py2.py3-none-any.whl (6.0 kB)
Requirement already satisfied: Flask<2.3.0,>=1.0.4 in /usr/local/lib/python3.10/dist-packages (from dash>=1.0.0->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3->interpret) (2.2.5)
Collecting Werkzeug<2.3.0 (from dash>=1.0.0->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3->interpret)
  Downloading Werkzeug-2.2.3-py3-none-any.whl (233 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 233.6/233.6 kB 28.5 MB/s eta 0:00:00
Requirement already satisfied: typing-extensions>=4.1.1 in /usr/local/lib/python3.10/dist-packages (from dash>=1.0.0->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3->interpret) (4.7.1)
Collecting retrying (from dash>=1.0.0->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3->interpret)
  Downloading retrying-1.3.4-py3-none-any.whl (11 kB)
Collecting ansi2html (from dash>=1.0.0->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3->interpret)
  Downloading ansi2html-1.8.0-py3-none-any.whl (16 kB)
Requirement already satisfied: nest-asyncio in /usr/local/lib/python3.10/dist-packages (from dash>=1.0.0->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3->interpret) (1.5.6)
Collecting zope.event (from gevent>=1.3.6->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3->interpret)
  Downloading zope.event-5.0-py3-none-any.whl (6.8 kB)
Collecting zope.interface (from gevent>=1.3.6->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3->interpret)
  Downloading zope.interface-6.0-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (246 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 247.0/247.0 kB 30.1 MB/s eta 0:00:00
Requirement already satisfied: greenlet>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from gevent>=1.3.6->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3->interpret) (2.0.2)
Requirement already satisfied: ipython-genutils in /usr/local/lib/python3.10/dist-packages (from ipykernel>=4.10.0->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3->interpret) (0.2.0)
Requirement already satisfied: traitlets>=4.1.0 in /usr/local/lib/python3.10/dist-packages (from ipykernel>=4.10.0->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3->interpret) (5.7.1)
Requirement already satisfied: jupyter-client in /usr/local/lib/python3.10/dist-packages (from ipykernel>=4.10.0->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3->interpret) (6.1.12)
Requirement already satisfied: tornado>=4.2 in /usr/local/lib/python3.10/dist-packages (from ipykernel>=4.10.0->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3->interpret) (6.3.1)
Requirement already satisfied: setuptools>=18.5 in /usr/local/lib/python3.10/dist-packages (from ipython>=5.5.0->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3->interpret) (67.7.2)
Collecting jedi>=0.16 (from ipython>=5.5.0->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3->interpret)
  Downloading jedi-0.19.0-py2.py3-none-any.whl (1.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 95.2 MB/s eta 0:00:00
Requirement already satisfied: decorator in /usr/local/lib/python3.10/dist-packages (from ipython>=5.5.0->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3->interpret) (4.4.2)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.10/dist-packages (from ipython>=5.5.0->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3->interpret) (0.7.5)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from ipython>=5.5.0->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3->interpret) (3.0.39)
Requirement already satisfied: pygments in /usr/local/lib/python3.10/dist-packages (from ipython>=5.5.0->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3->interpret) (2.14.0)
Requirement already satisfied: backcall in /usr/local/lib/python3.10/dist-packages (from ipython>=5.5.0->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3->interpret) (0.2.0)
Requirement already satisfied: matplotlib-inline in /usr/local/lib/python3.10/dist-packages (from ipython>=5.5.0->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3->interpret) (0.1.6)
Requirement already satisfied: pexpect>4.3 in /usr/local/lib/python3.10/dist-packages (from ipython>=5.5.0->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3->interpret) (4.8.0)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.10/dist-packages (from lime>=0.1.1.33->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3->interpret) (3.7.1)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from lime>=0.1.1.33->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3->interpret) (4.65.0)
Requirement already satisfied: scikit-image>=0.12 in /usr/local/lib/python3.10/dist-packages (from lime>=0.1.1.33->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3->interpret) (0.19.3)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=0.19.2->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3->interpret) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=0.19.2->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3->interpret) (2022.7.1)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from plotly>=3.8.1->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3->interpret) (8.2.2)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3->interpret) (1.26.16)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3->interpret) (2023.7.22)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3->interpret) (2.0.12)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3->interpret) (3.4)
Collecting multiprocess (from SALib>=1.3.3->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3->interpret)
  Downloading multiprocess-0.70.15-py310-none-any.whl (134 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.8/134.8 kB 18.2 MB/s eta 0:00:00
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=0.18.1->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3->interpret) (3.2.0)
Requirement already satisfied: packaging>20.9 in /usr/local/lib/python3.10/dist-packages (from shap>=0.28.5->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3->interpret) (23.1)
Collecting slicer==0.0.7 (from shap>=0.28.5->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3->interpret)
  Downloading slicer-0.0.7-py3-none-any.whl (14 kB)
Requirement already satisfied: numba in /usr/local/lib/python3.10/dist-packages (from shap>=0.28.5->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3->interpret) (0.56.4)
Requirement already satisfied: cloudpickle in /usr/local/lib/python3.10/dist-packages (from shap>=0.28.5->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3->interpret) (2.2.1)
Requirement already satisfied: Jinja2>=3.0 in /usr/local/lib/python3.10/dist-packages (from Flask<2.3.0,>=1.0.4->dash>=1.0.0->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3->interpret) (3.1.2)
Requirement already satisfied: itsdangerous>=2.0 in /usr/local/lib/python3.10/dist-packages (from Flask<2.3.0,>=1.0.4->dash>=1.0.0->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3->interpret) (2.1.2)
Requirement already satisfied: click>=8.0 in /usr/local/lib/python3.10/dist-packages (from Flask<2.3.0,>=1.0.4->dash>=1.0.0->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3->interpret) (8.1.6)
Requirement already satisfied: parso<0.9.0,>=0.8.3 in /usr/local/lib/python3.10/dist-packages (from jedi>=0.16->ipython>=5.5.0->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3->interpret) (0.8.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->lime>=0.1.1.33->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3->interpret) (1.1.0)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib->lime>=0.1.1.33->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3->interpret) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->lime>=0.1.1.33->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3->interpret) (4.41.1)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->lime>=0.1.1.33->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3->interpret) (1.4.4)

In [2]:
!pip install nodegam
from nodegam.sklearn import NodeGAMRegressor, NodeGAMClassifier
from nodegam.gams.MySpline import MySplineLogisticGAM, MySplineGAM
from nodegam.gams.MyEBM import MyExplainableBoostingClassifier, MyExplainableBoostingRegressor
from nodegam.gams.MyXGB import MyXGBOnehotClassifier, MyXGBOnehotRegressor
from nodegam.gams.MyBagging import MyBaggingClassifier, MyBaggingRegressor
from nodegam.utils import sigmoid_np, average_GAM_dfs
from nodegam.vis_utils import vis_GAM_effects

Collecting nodegam
  Downloading nodegam-0.3.0-py3-none-any.whl (77 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.1/77.1 kB 2.4 MB/s eta 0:00:00
Requirement already satisfied: torch>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from nodegam) (2.0.1+cu118)
Requirement already satisfied: numpy>=0.13 in /usr/local/lib/python3.10/dist-packages (from nodegam) (1.22.4)
Requirement already satisfied: scipy>=1.2.0 in /usr/local/lib/python3.10/dist-packages (from nodegam) (1.10.1)
Requirement already satisfied: scikit-learn>=0.17 in /usr/local/lib/python3.10/dist-packages (from nodegam) (1.2.2)
Collecting catboost>=0.12.2 (from nodegam)
  Downloading catboost-1.2-cp310-cp310-manylinux2014_x86_64.whl (98.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.6/98.6 MB 8.4 MB/s eta 0:00:00
Requirement already satisfied: xgboost>=0.81 in /usr/local/lib/python3.10/dist-packages (from nodegam) (1.7.6)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.10/dist-packages (from nodegam) (3.7.1)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from nodegam) (4.65.0)
Collecting tensorboardX (from nodegam)
  Downloading tensorboardX-2.6.2-py2.py3-none-any.whl (101 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 101.6/101.6 kB 5.7 MB/s eta 0:00:00
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from nodegam) (1.5.3)
Requirement already satisfied: prefetch-generator in /usr/local/lib/python3.10/dist-packages (from nodegam) (1.0.3)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from nodegam) (2.27.1)
Collecting category-encoders (from nodegam)
  Downloading category_encoders-2.6.1-py2.py3-none-any.whl (81 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 81.9/81.9 kB 10.9 MB/s eta 0:00:00
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from nodegam) (3.12.2)
Collecting qhoptim (from nodegam)
  Downloading qhoptim-1.1.0-py3-none-any.whl (20 kB)
Collecting mat4py (from nodegam)
  Downloading mat4py-0.5.0-py2.py3-none-any.whl (13 kB)
Requirement already satisfied: interpret>=0.2 in /usr/local/lib/python3.10/dist-packages (from nodegam) (0.4.3)
Collecting pygam (from nodegam)
  Downloading pygam-0.9.0-py3-none-any.whl (522 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 522.2/522.2 kB 26.6 MB/s eta 0:00:00
Requirement already satisfied: seaborn in /usr/local/lib/python3.10/dist-packages (from nodegam) (0.12.2)
Requirement already satisfied: graphviz in /usr/local/lib/python3.10/dist-packages (from catboost>=0.12.2->nodegam) (0.20.1)
Requirement already satisfied: plotly in /usr/local/lib/python3.10/dist-packages (from catboost>=0.12.2->nodegam) (5.13.1)
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from catboost>=0.12.2->nodegam) (1.16.0)
Requirement already satisfied: interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3 in /usr/local/lib/python3.10/dist-packages (from interpret>=0.2->nodegam) (0.4.3)
Requirement already satisfied: psutil>=5.6.2 in /usr/local/lib/python3.10/dist-packages (from interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3->interpret>=0.2->nodegam) (5.9.5)
Requirement already satisfied: ipykernel>=4.10.0 in /usr/local/lib/python3.10/dist-packages (from interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3->interpret>=0.2->nodegam) (5.5.6)
Requirement already satisfied: ipython>=5.5.0 in /usr/local/lib/python3.10/dist-packages (from interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3->interpret>=0.2->nodegam) (7.34.0)
Requirement already satisfied: skope-rules>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3->interpret>=0.2->nodegam) (1.0.1)
Requirement already satisfied: SALib>=1.3.3 in /usr/local/lib/python3.10/dist-packages (from interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3->interpret>=0.2->nodegam) (1.4.7)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.10/dist-packages (from interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3->interpret>=0.2->nodegam) (1.3.1)
Requirement already satisfied: treeinterpreter>=0.2.2 in /usr/local/lib/python3.10/dist-packages (from interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3->interpret>=0.2->nodegam) (0.2.3)
Requirement already satisfied: lime>=0.1.1.33 in /usr/local/lib/python3.10/dist-packages (from interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3->interpret>=0.2->nodegam) (0.2.0.1)
Requirement already satisfied: shap>=0.28.5 in /usr/local/lib/python3.10/dist-packages (from interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3->interpret>=0.2->nodegam) (0.42.1)
Requirement already satisfied: dill>=0.2.5 in /usr/local/lib/python3.10/dist-packages (from interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3->interpret>=0.2->nodegam) (0.3.7)
Requirement already satisfied: dash>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3->interpret>=0.2->nodegam) (2.11.1)
Requirement already satisfied: dash-core-components>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3->interpret>=0.2->nodegam) (2.0.0)
Requirement already satisfied: dash-html-components>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3->interpret>=0.2->nodegam) (2.0.0)
Requirement already satisfied: dash-table>=4.1.0 in /usr/local/lib/python3.10/dist-packages (from interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3->interpret>=0.2->nodegam) (5.0.0)
Requirement already satisfied: dash-cytoscape>=0.1.1 in /usr/local/lib/python3.10/dist-packages (from interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3->interpret>=0.2->nodegam) (0.3.0)
Requirement already satisfied: gevent>=1.3.6 in /usr/local/lib/python3.10/dist-packages (from interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3->interpret>=0.2->nodegam) (23.7.0)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas->nodegam) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->nodegam) (2022.7.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->nodegam) (1.26.16)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->nodegam) (2023.7.22)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.10/dist-packages (from requests->nodegam) (2.0.12)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->nodegam) (3.4)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=0.17->nodegam) (3.2.0)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.10/dist-packages (from torch>=1.1.0->nodegam) (4.7.1)
Requirement already satisfied: sympy in /usr/local/lib/python3.10/dist-packages (from torch>=1.1.0->nodegam) (1.11.1)
Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch>=1.1.0->nodegam) (3.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch>=1.1.0->nodegam) (3.1.2)
Requirement already satisfied: triton==2.0.0 in /usr/local/lib/python3.10/dist-packages (from torch>=1.1.0->nodegam) (2.0.0)
Requirement already satisfied: cmake in /usr/local/lib/python3.10/dist-packages (from triton==2.0.0->torch>=1.1.0->nodegam) (3.25.2)
Requirement already satisfied: lit in /usr/local/lib/python3.10/dist-packages (from triton==2.0.0->torch>=1.1.0->nodegam) (16.0.6)
Requirement already satisfied: statsmodels>=0.9.0 in /usr/local/lib/python3.10/dist-packages (from category-encoders->nodegam) (0.13.5)
Requirement already satisfied: patsy>=0.5.1 in /usr/local/lib/python3.10/dist-packages (from category-encoders->nodegam) (0.5.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->nodegam) (1.1.0)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib->nodegam) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->nodegam) (4.41.1)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->nodegam) (1.4.4)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->nodegam) (23.1)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->nodegam) (9.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->nodegam) (3.1.0)
Collecting numpy>=0.13 (from nodegam)
  Downloading numpy-1.25.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.2/18.2 MB 49.1 MB/s eta 0:00:00
Requirement already satisfied: progressbar2<5.0.0,>=4.2.0 in /usr/local/lib/python3.10/dist-packages (from pygam->nodegam) (4.2.0)
Requirement already satisfied: protobuf in /usr/local/lib/python3.10/dist-packages (from tensorboardX->nodegam) (3.20.3)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from plotly->catboost>=0.12.2->nodegam) (8.2.2)
Requirement already satisfied: python-utils>=3.0.0 in /usr/local/lib/python3.10/dist-packages (from progressbar2<5.0.0,>=4.2.0->pygam->nodegam) (3.7.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch>=1.1.0->nodegam) (2.1.3)
Requirement already satisfied: mpmath>=0.19 in /usr/local/lib/python3.10/dist-packages (from sympy->torch>=1.1.0->nodegam) (1.3.0)
Requirement already satisfied: Flask<2.3.0,>=1.0.4 in /usr/local/lib/python3.10/dist-packages (from dash>=1.0.0->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3->interpret>=0.2->nodegam) (2.2.5)
Requirement already satisfied: Werkzeug<2.3.0 in /usr/local/lib/python3.10/dist-packages (from dash>=1.0.0->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3->interpret>=0.2->nodegam) (2.2.3)
Requirement already satisfied: retrying in /usr/local/lib/python3.10/dist-packages (from dash>=1.0.0->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3->interpret>=0.2->nodegam) (1.3.4)
Requirement already satisfied: ansi2html in /usr/local/lib/python3.10/dist-packages (from dash>=1.0.0->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3->interpret>=0.2->nodegam) (1.8.0)
Requirement already satisfied: nest-asyncio in /usr/local/lib/python3.10/dist-packages (from dash>=1.0.0->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3->interpret>=0.2->nodegam) (1.5.6)
Requirement already satisfied: zope.event in /usr/local/lib/python3.10/dist-packages (from gevent>=1.3.6->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3->interpret>=0.2->nodegam) (5.0)
Requirement already satisfied: zope.interface in /usr/local/lib/python3.10/dist-packages (from gevent>=1.3.6->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3->interpret>=0.2->nodegam) (6.0)
Requirement already satisfied: greenlet>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from gevent>=1.3.6->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3->interpret>=0.2->nodegam) (2.0.2)
Requirement already satisfied: ipython-genutils in /usr/local/lib/python3.10/dist-packages (from ipykernel>=4.10.0->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3->interpret>=0.2->nodegam) (0.2.0)
Requirement already satisfied: traitlets>=4.1.0 in /usr/local/lib/python3.10/dist-packages (from ipykernel>=4.10.0->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3->interpret>=0.2->nodegam) (5.7.1)
Requirement already satisfied: jupyter-client in /usr/local/lib/python3.10/dist-packages (from ipykernel>=4.10.0->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3->interpret>=0.2->nodegam) (6.1.12)
Requirement already satisfied: tornado>=4.2 in /usr/local/lib/python3.10/dist-packages (from ipykernel>=4.10.0->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3->interpret>=0.2->nodegam) (6.3.1)
Requirement already satisfied: setuptools>=18.5 in /usr/local/lib/python3.10/dist-packages (from ipython>=5.5.0->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3->interpret>=0.2->nodegam) (67.7.2)
Requirement already satisfied: jedi>=0.16 in /usr/local/lib/python3.10/dist-packages (from ipython>=5.5.0->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3->interpret>=0.2->nodegam) (0.19.0)
Requirement already satisfied: decorator in /usr/local/lib/python3.10/dist-packages (from ipython>=5.5.0->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3->interpret>=0.2->nodegam) (4.4.2)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.10/dist-packages (from ipython>=5.5.0->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3->interpret>=0.2->nodegam) (0.7.5)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from ipython>=5.5.0->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3->interpret>=0.2->nodegam) (3.0.39)
Requirement already satisfied: pygments in /usr/local/lib/python3.10/dist-packages (from ipython>=5.5.0->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3->interpret>=0.2->nodegam) (2.14.0)
Requirement already satisfied: backcall in /usr/local/lib/python3.10/dist-packages (from ipython>=5.5.0->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3->interpret>=0.2->nodegam) (0.2.0)
Requirement already satisfied: matplotlib-inline in /usr/local/lib/python3.10/dist-packages (from ipython>=5.5.0->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3->interpret>=0.2->nodegam) (0.1.6)
Requirement already satisfied: pexpect>4.3 in /usr/local/lib/python3.10/dist-packages (from ipython>=5.5.0->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3->interpret>=0.2->nodegam) (4.8.0)
Requirement already satisfied: scikit-image>=0.12 in /usr/local/lib/python3.10/dist-packages (from lime>=0.1.1.33->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3->interpret>=0.2->nodegam) (0.19.3)
Requirement already satisfied: multiprocess in /usr/local/lib/python3.10/dist-packages (from SALib>=1.3.3->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3->interpret>=0.2->nodegam) (0.70.15)
Requirement already satisfied: slicer==0.0.7 in /usr/local/lib/python3.10/dist-packages (from shap>=0.28.5->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3->interpret>=0.2->nodegam) (0.0.7)
Requirement already satisfied: numba in /usr/local/lib/python3.10/dist-packages (from shap>=0.28.5->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3->interpret>=0.2->nodegam) (0.56.4)
Requirement already satisfied: cloudpickle in /usr/local/lib/python3.10/dist-packages (from shap>=0.28.5->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3->interpret>=0.2->nodegam) (2.2.1)
Requirement already satisfied: itsdangerous>=2.0 in /usr/local/lib/python3.10/dist-packages (from Flask<2.3.0,>=1.0.4->dash>=1.0.0->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3->interpret>=0.2->nodegam) (2.1.2)
Requirement already satisfied: click>=8.0 in /usr/local/lib/python3.10/dist-packages (from Flask<2.3.0,>=1.0.4->dash>=1.0.0->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3->interpret>=0.2->nodegam) (8.1.6)
Requirement already satisfied: parso<0.9.0,>=0.8.3 in /usr/local/lib/python3.10/dist-packages (from jedi>=0.16->ipython>=5.5.0->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3->interpret>=0.2->nodegam) (0.8.3)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.10/dist-packages (from pexpect>4.3->ipython>=5.5.0->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3->interpret>=0.2->nodegam) (0.7.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.10/dist-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=5.5.0->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,skoperules,treeinterpreter]==0.4.3->interpret>=0.2->nodegam) (0.2.6)

WARNING! The apex is not installed so fp16 is not available.

In [3]:
def kl_divergence(predicted_mu, predicted_sigma, y_test):
    y_dist = np.expand_dims(y_test, 1)
    y_dist = y_dist.astype(np.float32)


    if predicted_mu.shape != (len(y_test), 1):
        predicted_mu = np.expand_dims(y_test, 1)
    try:
        predicted_mu = predicted_mu.astype(np.float32)
    except:
        pass

    try:
        predicted_sigma = predicted_sigma.astype(np.float32)
    except:
        pass

    t = tfd.Normal(loc=y_dist, scale=np.std(y_dist))

    p = tfd.Normal(loc=predicted_mu, scale=predicted_sigma)


    kl = tf.reduce_mean(tfd.kl_divergence(t, p, allow_nan_stats=True))

    return kl.numpy()


def stable_kl_div(predicted_mu, predicted_sigma, y_test):
    y_dist = np.expand_dims(y_test, 1)
    y_dist = y_dist.astype(np.float32)


    if predicted_mu.shape != (len(y_test), 1):
        predicted_mu = np.expand_dims(y_test, 1)
    try:
        predicted_mu = predicted_mu.astype(np.float32)
    except:
        pass

    try:
        predicted_sigma = predicted_sigma.astype(np.float32)
    except:
        pass

    t = tfd.Normal(loc=y_dist, scale=np.std(y_dist)).log_prob(y_dist)

    p = tfd.Normal(loc=predicted_mu, scale=predicted_sigma).log_prob(predicted_mu)

    # Calculate the mean KL divergence using the log PDFs
    kl_divergence = tf.reduce_mean(p - t)

    return kl_divergence.numpy()


def compute_wasserstein_distance(p, q):
    return wasserstein_distance(p, q)

from scipy.stats import norm


def crps(predicted_mean, predicted_std, true_value):
    """
    Calculate the Continuous Ranked Probability Score (CRPS) for a normal distribution.

    Parameters:
    predicted_mean (float or numpy array): Predicted mean.
    predicted_std (float or numpy array): Predicted standard deviation.
    true_value (float or numpy array): True value(s).

    Returns:
    float: CRPS score.
    """
    cdf_diff = (norm.cdf(true_value, loc=predicted_mean, scale=predicted_std) -
                np.where(true_value >= predicted_mean, 1, 0))
    crps = np.mean(cdf_diff ** 2)
    return crps

def crps_norm(y_true, mu, sigma=None):
    if sigma is None:
      crps = ps.crps_ensemble(y_true, mu).mean()
    else:
      crps = ps.crps_gaussian(y_true, mu, sigma).mean()

    return crps

In [4]:

####################################### NAM EXU-activation Layer
class ExuLayer(tf.keras.layers.Layer):
    def __init__(self, units=32, input_dim=32):
        super(ExuLayer, self).__init__()
        w_init = tf.random_normal_initializer()
        self.w = tf.Variable(
            initial_value=w_init(shape=(input_dim, units), dtype="float32"),
            trainable=True,
        )
        b_init = tf.zeros_initializer()
        self.b = tf.Variable(
            initial_value=b_init(shape=(units,), dtype="float32"), trainable=True
        )

    def call(self, inputs):
        return tf.clip_by_value(tf.matmul(inputs, tf.exp(self.w)) + self.b, 0, 1)

In [5]:
class CustomPipeline(Pipeline):
    """Custom sklearn Pipeline to transform data."""

    def apply_transformation(self, x):
        """Applies all transforms to the data, without applying last estimator.

        Args:
          x: Iterable data to predict on. Must fulfill input requirements of first
            step of the pipeline.

        Returns:
          xt: Transformed data.
        """
        xt = x
        for _, transform in self.steps[:-1]:
            xt = transform.fit_transform(xt)
        return xt


def transform_data(df):
    """Apply a fixed set of transformations to the pd.Dataframe `df`.

    Args:
      df: Input dataframe containing features.

    Returns:
      Transformed dataframe and corresponding column names. The transformations
      include (1) encoding categorical features as a one-hot numeric array, (2)
      identity `FunctionTransformer` for numerical variables. This is followed by
      scaling all features to the range (-1, 1) using min-max scaling.
    """
    column_names = df.columns
    new_column_names = []
    is_categorical = np.array([dt.kind == "O" for dt in df.dtypes])
    categorical_cols = df.columns.values[is_categorical]
    numerical_cols = df.columns.values[~is_categorical]
    for index, is_cat in enumerate(is_categorical):
        col_name = column_names[index]
        if is_cat:
            new_column_names += [
                "{}: {}".format(col_name, val) for val in set(df[col_name])
            ]
        else:
            new_column_names.append(col_name)
    cat_ohe_step = ("ohe", OneHotEncoder(sparse=False, handle_unknown="ignore"))

    cat_pipe = Pipeline([cat_ohe_step])
    num_pipe = Pipeline([("identity", FunctionTransformer(validate=True))])
    transformers = [
        ("cat", cat_pipe, categorical_cols),
        ("num", num_pipe, numerical_cols),
    ]
    column_transform = ColumnTransformer(transformers=transformers)

    pipe = CustomPipeline(
        [
            ("column_transform", column_transform),
            ("min_max", MinMaxScaler((-1, 1))),
            ("dummy", None),
        ]
    )
    df = pipe.apply_transformation(df)
    return df, new_column_names

In [6]:



######################################################### Model builder


############################### Helper functions for building MLP, NAM and NAMLSS
def built_DNN(input, output_activation="linear", output_num=1):
    x = Dense(1000, "relu")(input)
    x = Dropout(0.5)(x)
    x = Dense(500, "relu")(x)
    x = Dropout(0.5)(x)
    x = Dense(50, "relu")(x)
    x = Dense(25, "relu")(x)
    #x = Dense(128, "relu")(input)
    #x = Dropout(0.3)(x)
    #x = Dense(64, "relu")(x)
    #x = Dropout(0.3)(x)
    #x = Dense(32, "relu")(x)
    x = Dense(output_num, activation=output_activation, use_bias=False)(x)
    model_dnn = Model(inputs=input, outputs=x)
    model_dnn.reset_states()
    return model_dnn


def LINEAR(x):
    return x


################# MLP
def MLP(
    features_train,
    labels_train,
    features_test,
    labels_test,
    metrics=[tf.keras.metrics.RootMeanSquaredError(name="rmse"), "mse"],
    output_activation="linear",
):
    inps = Input(shape=(features_train.shape[1],))
    model = built_DNN(inps, output_activation=output_activation)

    model.compile(
        loss=POINT_LOSS, metrics=metrics, optimizer=Adam(learning_rate=LEARNING_RATE)
    )

    history = model.fit(
        x=features_train,
        y=labels_train,
        epochs=NUM_EPOCHS,
        callbacks=[EARLY_STOPPING, REDUCE_LR],
        batch_size=BATCH_SIZE,
        verbose=0,
    )

    loc_pred = model.predict(features_test)
    loc_pred = np.array([loc_pred[i][0] for i in range(len(loc_pred))], dtype=np.float64)
    likelihood = LL_EVAL(loc_pred, labels_test)

    ll, point_loss, kl, skl, ws, crsp = LL_EVAL(loc_pred, labels_test)

    return ll, point_loss, kl, skl, ws, crsp


######################## Distributional DNN


def DDNN(
    features_train,
    labels_train,
    features_test,
    labels_test,
    metrics=[tf.keras.metrics.RootMeanSquaredError(name="rmse"), "mse"],
    distribution=tfd.Normal,
    loc_activation=LINEAR,
    scale_activation=tf.math.softplus,
    output_num=2,
):
    # Create inputs
    inps = Input(shape=(features_train.shape[1],))
    ms = built_DNN(inps, "linear", output_num)
    z = ms.output

    # built distributional layer
    # Change for when dist params have different names
    p_y = tfp.layers.DistributionLambda(
        lambda x: distribution(
            loc=loc_activation(x[:, 0]), scale=scale_activation(x[:, 1])
        )
    )(z)

    model = Model(inputs=ms.input, outputs=p_y)

    def NLL(y_true, y_hat):
        return -y_hat.log_prob(y_true)

    model.compile(
        loss=NLL, metrics=metrics, optimizer=Adam(learning_rate=LEARNING_RATE)
    )

    history = model.fit(
        x=features_train,
        y=labels_train,
        epochs=NUM_EPOCHS,
        callbacks=[EARLY_STOPPING, REDUCE_LR],
        batch_size=BATCH_SIZE,
        verbose=0,
    )

    # Evaluate model
    preds = ms(features_test)
    mu_preds = np.array(
        loc_activation(preds[:, 0])
    )
    sigma_preds = np.array(
        [
            scale_activation(preds[:, 1])
        ]
    )

    ll, point_loss, kl, skl, ws, crsp = LL_EVAL(mu_preds, labels_test, sigma_preds)

    return ll, point_loss, kl, skl, ws, crsp


######################################### NAM


def NAM(
    features_train,
    labels_train,
    features_test,
    labels_test,
    metrics=[tf.keras.metrics.RootMeanSquaredError(name="rmse"), "mse"],
    output_activation="linear",
):
    inps = [Input(shape=(1,)) for _ in range(features_train.shape[1])]

    # define submodels
    # same architecture as for DNN and MLP
    ms = [
        built_DNN(inps[i], output_activation=output_activation)
        for i in range(features_train.shape[1])
    ]
    z = sum([m.output for m in ms])
    model = Model(inputs=[m.input for m in ms], outputs=z)

    model.compile(
        loss=POINT_LOSS, metrics=metrics, optimizer=Adam(learning_rate=LEARNING_RATE)
    )

    training_data = [features_train[:,i] for i in range(features_train.shape[1])]
    eval_data = [features_test[:,i] for i in range(features_test.shape[1])]

    history = model.fit(
        x=training_data,
        y=labels_train,
        epochs=NUM_EPOCHS,
        callbacks=[EARLY_STOPPING, REDUCE_LR],
        batch_size=BATCH_SIZE,
        verbose=0,
    )

    loc_pred = model.predict(eval_data)
    loc_pred = np.array([loc_pred[i][0] for i in range(len(loc_pred))], dtype=np.float64)
    ll, point_loss, kl, skl, ws, crsp = LL_EVAL(loc_pred, labels_test)

    return ll, point_loss, kl, skl, ws, crsp


############################################ NAMLSS


def define_models_scale(input):
    x = Dense(50, activation="relu")(input)
    x = Dense(25, activation="relu")(x)
    x = Dense(1, activation="linear", use_bias=False)(x)
    x = Model(inputs=input, outputs=x)
    # x.reset_states()
    return x


def NAMLSS(
    features_train,
    labels_train,
    features_test,
    labels_test,
    metrics=[tf.keras.metrics.RootMeanSquaredError(name="rmse"), "mse"],
    distribution=tfd.Normal,
    loc_activation=LINEAR,
    scale_activation=tf.math.softplus,
    output_num=1,
):
    training_data = 2 * [features_train[:, i] for i in range(features_train.shape[1])]
    eval_data = 2 * [features_test[:, i] for i in range(features_test.shape[1])]

    inps = [Input(shape=(1,)) for _ in range(2 * features_train.shape[1])]

    ms = [built_DNN(inps[i]) for i in range(features_train.shape[1])]
    ms += [
        define_models_scale(inps[i + features_train.shape[1]])
        for i in range(features_train.shape[1])
    ]

    z1 = sum([m.output for m in ms[: features_train.shape[1]]])
    z2 = sum([m.output for m in ms[features_train.shape[1] :]])

    z = concatenate([z1, z2])

    # Change for when dist params have different names
    p_y = tfp.layers.DistributionLambda(
        lambda x: distribution(
            loc=loc_activation(x[:, 0]), scale=scale_activation(x[:, 1])
        )
    )(z)

    model = Model(inputs=[m.input for m in ms], outputs=p_y)

    def NLL(y_true, y_hat):
        return -y_hat.log_prob(y_true)

    model.compile(
        loss=NLL, metrics=metrics, optimizer=Adam(learning_rate=LEARNING_RATE)
    )

    history = model.fit(
        x=training_data,
        y=labels_train,
        validation_split=0.2,
        epochs=NUM_EPOCHS,
        callbacks=[EARLY_STOPPING, REDUCE_LR],
        batch_size=BATCH_SIZE,
        verbose=0,
    )

    preds = [ms[idx].predict(eval_data[idx], verbose=0) for idx in range(len(eval_data))]
    preds_mu = preds[:features_test.shape[1]]
    preds_sigma = preds[features_test.shape[1]:]

    mu = sum(preds_mu)
    sigma = sum(preds_sigma)
    mu_preds = loc_activation(mu)
    sigma_preds = scale_activation(sigma)

    mu = np.array([mu_preds[i][0] for i in range(len(mu_preds))])
    sigma = np.array([sigma_preds[i][0] for i in range(len(sigma_preds))])

    ll, point_loss, kl, skl, ws, crsp = LL_EVAL(mu, labels_test, sigma)

    return ll, point_loss, kl, skl, ws, crsp


#### NAMLSS 2
def NA2MLSS(
    features_train,
    labels_train,
    features_test,
    labels_test,
    metrics=[tf.keras.metrics.RootMeanSquaredError(name="rmse"), "mse"],
    distribution=tfd.Normal,
    loc_activation=LINEAR,
    scale_activation=tf.math.softplus,
    output_num=2,
):
    training_data = [features_train[:, i] for i in range(features_train.shape[1])]
    eval_data = [features_test[:, i] for i in range(features_test.shape[1])]

    inps = [Input(shape=(1,)) for _ in range(features_train.shape[1])]

    ms = [
        built_DNN(inps[i], output_num=output_num)
        for i in range(features_train.shape[1])
    ]

    z = sum([m.output for m in ms])

    # Change for when dist params have different names
    p_y = tfp.layers.DistributionLambda(
        lambda x: distribution(
            loc=loc_activation(x[:, 0]), scale=scale_activation(x[:, 1])
        )
    )(z)

    model = Model(inputs=[m.input for m in ms], outputs=p_y)

    def NLL(y_true, y_hat):
        return -y_hat.log_prob(y_true)

    model.compile(
        loss=NLL, metrics=metrics, optimizer=Adam(learning_rate=LEARNING_RATE)
    )

    history = model.fit(
        x=training_data,
        y=labels_train,
        epochs=NUM_EPOCHS,
        callbacks=[EARLY_STOPPING, REDUCE_LR],
        batch_size=BATCH_SIZE,
        verbose=0,
    )

    preds = [ms[idx].predict(eval_data[idx], verbose=0) for idx in range(len(eval_data))]

    preds = sum(preds)
    mu, sigma = preds[:,0], preds[:, 1]
    mu_preds = loc_activation(mu)
    sigma_preds = scale_activation(sigma)

    ll, point_loss, kl, skl, ws, crsp = LL_EVAL(mu_preds, labels_test, sigma_preds)

    return ll, point_loss, kl, skl, ws, crsp


###################### XGBoost
def XGB(features_train, labels_train, features_test, labels_test, regression=True):
    if regression:
        model = XGBRegressor()
    else:
        model = XGBClassifier()
    model.fit(features_train, labels_train)

    preds = model.predict(features_test)

    ll, point_loss, kl, skl, ws, crsp = LL_EVAL(np.float64(preds), labels_test)

    return ll, point_loss, kl, skl, ws, crsp




############## EBM
def EBM(features_train, labels_train, features_test, labels_test, regression=True):
    if regression:
        model = ExplainableBoostingRegressor()
    else:
        model = ExplainableBoostingClassifier()

    model.fit(features_train, labels_train)

    preds = model.predict(features_test)

    ll, point_loss, kl, skl, ws, crsp = LL_EVAL(np.float64(preds), labels_test)

    return ll, point_loss, kl, skl, ws, crsp


############################## NODEGAM
def NODEGAM(features_train, labels_train, features_test, labels_test, regression=True):
    if regression:
        model = NodeGAMRegressor(
            in_features=features_train.shape[1], verbose=0, seed=141, ga2m=0
        )
    else:
        model = NodeGAMClassifier(
            in_features=features_train.shape[1],
            verbose=0,
            seed=141,
            ga2m=0,
        )

    X_train = pd.DataFrame(np.vstack([features_train])).reset_index(drop=True)
    X_test = pd.DataFrame(np.vstack([features_test])).reset_index(drop=True)
    record = model.fit(X_train, np.array(labels_train))
    preds = model.predict(X_test)

    ll, point_loss, kl, skl, ws, crsp = LL_EVAL(np.float64(preds), labels_test)

    return ll, point_loss, kl, skl, ws, crsp

In [7]:

if __name__ == "__main__":
    # task:
    REGRESSION = True
    # general arguments
    BATCH_SIZE = 1024
    NUM_EPOCHS = 2000
    LEARNING_RATE = 0.001
    NUM_FOLDS = 5

    # loss func for point estimators
    POINT_LOSS = "mse"

    EARLY_STOPPING = EarlyStopping(
        patience=150, restore_best_weights=True, min_delta=1e-05, monitor="loss"
    )

    METRICS = [tf.keras.metrics.RootMeanSquaredError(name="rmse"), "mse"]

    REDUCE_LR = ReduceLROnPlateau(
        monitor="loss", factor=0.95, patience=25, min_delta=1e-05
    )

    KFOLD = KFold(n_splits=NUM_FOLDS, shuffle=True, random_state=101)

    DISTRIBUTION = tfd.Normal

    # Define distribution that is modelled
    def LL_EVAL(loc, y_true, scale=None):
        if scale is None:
          dist = DISTRIBUTION(loc, scale=np.std(y_true))
        else:
          dist = DISTRIBUTION(loc, scale=scale)
        ll = - tf.reduce_sum(dist.log_prob(value=y_true)).numpy()
        point_loss = mean_squared_error(y_true, loc)

        crsp = crps_norm(y_true, loc, scale)
        wasserstein = compute_wasserstein_distance(y_true, loc)
        if scale is None:
          kl_div = kl_divergence(loc, np.std(loc), y_true)
          skl_div = stable_kl_div(loc, np.std(loc), y_true)
        else:
          kl_div = kl_divergence(loc, scale, y_true)
          skl_div = stable_kl_div(loc, scale, y_true)

        print(ll, point_loss, kl_div, skl_div, wasserstein, crsp)

        return ll, point_loss, kl_div, skl_div, wasserstein, crsp


    from sklearn import datasets
    housing = datasets.fetch_california_housing()

    X = pd.DataFrame(data=housing.data, columns=housing.feature_names)

    targets = housing.target
    df = pd.DataFrame(X, columns=housing.feature_names)
    df["targets"] = housing.target

    from scipy import stats
    df = df[(np.abs(stats.zscore(df)) < 10).all(axis=1)]
    df = df.reset_index(drop=True)


    X = df[housing.feature_names]
    targets = np.array(df["targets"])
    # Always use transform_data function on X
    features, cols = transform_data(X)

    scaler = StandardScaler().fit(np.array(targets).reshape(-1, 1))
    targets = scaler.transform(np.array(targets).reshape(-1, 1)).flatten()

    fold_no = 1

    model_list = [
        "MLP",
        "DDNN",
        "NAMLSS",
        "NA2MLSS",
        "NAM",
        "XGBOOST",
        "EBM",
        "NODEGAM",
    ]

    results = pd.DataFrame(columns=["Model", "Likelihood", "MSE", "KL", "SKL", "Wasserstein", "CRSP"])

    for mod in model_list:
        print(mod)
        ll_per_fold = []
        mse_per_fold = []
        kl_div_per_fold = []
        skl_div_per_fold = []
        ws_dis_per_fold = []
        crsp_per_fold = []

        for train, test in tqdm(KFOLD.split(features, targets)):
            if mod == "DDNN":
                ll, pl, kl, skl, ws, crsp = DDNN(
                    features[train],
                    targets[train],
                    features[test],
                    targets[test],
                    metrics=METRICS,
                    distribution=DISTRIBUTION,
                    loc_activation=LINEAR,
                    scale_activation=tf.math.softplus,
                    output_num=2,
                )
            elif mod == "MLP":
                ll, pl, kl, skl, ws, crsp = MLP(
                    features[train],
                    targets[train],
                    features[test],
                    targets[test],
                    metrics=METRICS,
                    output_activation="linear",
                )

            elif mod == "NAM":
                ll, pl, kl, skl, ws, crsp = NAM(
                    features[train],
                    targets[train],
                    features[test],
                    targets[test],
                    metrics=METRICS,
                    output_activation="linear",
                )
            elif mod == "XGBOOST":
                ll, pl, kl, skl, ws, crsp = XGB(
                    features[train],
                    targets[train],
                    features[test],
                    targets[test],
                    REGRESSION,
                )
            elif mod == "EBM":
                ll, pl, kl, skl, ws, crsp = EBM(
                    features[train],
                    targets[train],
                    features[test],
                    targets[test],
                    REGRESSION,
                )
            elif mod == "NODEGAM":
                ll, pl, kl, skl, ws, crsp = NODEGAM(
                    features[train],
                    targets[train],
                    features[test],
                    targets[test],
                    REGRESSION,
                )
            elif mod == "NAMLSS":
                ll, pl, kl, skl, ws, crsp = NAMLSS(
                    features[train],
                    targets[train],
                    features[test],
                    targets[test],
                    metrics=METRICS,
                    distribution=DISTRIBUTION,
                    loc_activation=LINEAR,
                    scale_activation=tf.math.softplus,
                    output_num=1,
                )
            elif mod == "NA2MLSS":
                ll, pl, kl, skl, ws, crsp = NA2MLSS(
                    features[train],
                    targets[train],
                    features[test],
                    targets[test],
                    metrics=METRICS,
                    distribution=DISTRIBUTION,
                    loc_activation=LINEAR,
                    scale_activation=tf.math.softplus,
                    output_num=2,
                )

            ll_per_fold.append(ll)
            mse_per_fold.append(pl)
            kl_div_per_fold.append(kl)
            skl_div_per_fold.append(skl)
            ws_dis_per_fold.append(ws)
            crsp_per_fold.append(crsp)

        name = NUM_FOLDS*[mod]
        temp_df = pd.DataFrame(np.array((name, ll_per_fold, mse_per_fold, kl_div_per_fold, skl_div_per_fold, ws_dis_per_fold, crsp_per_fold)).T, columns=["Model", "Likelihood", "MSE", "KL", "SKL", "Wasserstein", "CRSP"])
        results = pd.concat([results, temp_df])

MLP

0it [00:00, ?it/s]

129/129 [==============================] - 0s 2ms/step

1it [02:23, 143.63s/it]

4075.105010193082 0.17546168267932588 0.0068698972 0.08065671 0.056812418087406766 0.26569868197236857
4075.105010193082 0.17546168267932588 0.0068698972 0.08065671 0.056812418087406766 0.26569868197236857
129/129 [==============================] - 0s 2ms/step

2it [04:15, 124.83s/it]

4202.759484232807 0.17164229845577397 0.0070975274 0.081946015 0.06219147373033417 0.26314588575996556
4202.759484232807 0.17164229845577397 0.0070975274 0.081946015 0.06219147373033417 0.26314588575996556
129/129 [==============================] - 0s 1ms/step

3it [06:38, 133.25s/it]

4184.5267890582 0.18363992870436083 0.0061323345 0.07631737 0.062337909051515886 0.26866546635716004
4184.5267890582 0.18363992870436083 0.0061323345 0.07631737 0.062337909051515886 0.26866546635716004
129/129 [==============================] - 0s 1ms/step
4129.846927558593 0.17257583702613602 0.010450482 0.09885967 0.08497044058771977 0.2639199608959798

4it [09:01, 137.04s/it]

4129.846927558593 0.17257583702613602 0.010450482 0.09885967 0.08497044058771977 0.2639199608959798
129/129 [==============================] - 0s 1ms/step

5it [11:24, 136.85s/it]

4124.335059740847 0.1682490052233794 0.008263618 0.088231385 0.06650459097054849 0.2585521124504477
4124.335059740847 0.1682490052233794 0.008263618 0.088231385 0.06650459097054849 0.2585521124504477
DDNN

1it [01:53, 113.84s/it]

1676.4606 0.1718022204304154 26.056719 1.3372209 0.058334755411331714 0.1929646876222129

2it [04:16, 130.80s/it]

1789.2252 0.17048690692730317 24.776987 1.365439 0.06465432048274154 0.1936152995881799

3it [06:39, 136.23s/it]

34677.586 0.17944181947185237 34.89226 1.3273281 0.06120851705337361 0.19527643735427713

4it [08:32, 127.28s/it]

2056.437 0.1810910645463642 26.654047 1.356321 0.07995300278710846 0.194906479365685

5it [10:55, 131.16s/it]

1966.9362 0.17312274555635335 25.083672 1.388209 0.0662588067917997 0.19017787077732007
NAMLSS

1it [09:49, 589.25s/it]

3430.7144 0.3461547601699664 5.264266 0.9832277 0.20336709554443205 0.2879006930373114

2it [20:23, 615.61s/it]

4282.4795 0.3558867903019335 5.5546207 1.0061556 0.21125258527113744 0.29111007002558265

3it [30:57, 623.95s/it]

3930.816 0.35147078433595647 5.1770945 0.9996402 0.2156643658568491 0.29190807374509764

4it [41:33, 629.00s/it]

3464.7886 0.31746283768819283 5.5160832 1.0287627 0.1945372910743919 0.2770220352961334

5it [51:24, 616.93s/it]

3314.3108 0.3445124986154068 4.649857 0.9658687 0.21500490908237554 0.28587326001687174
NA2MLSS

1it [01:10, 70.97s/it]

3002.241 0.33250888617323976 2.587397 0.8966106 0.21911380310482115 0.2820711494716398

2it [09:14, 313.75s/it]

3984.094 0.3462042408511004 4.737431 1.0354807 0.19090148906796942 0.29126958091081057

3it [12:09, 250.14s/it]

2335.5588 0.28382296185562983 2.7357328 0.86250037 0.19989560805801904 0.2611154868845405

4it [20:38, 352.49s/it]

2055.5752 0.24374778631244473 3.2340446 0.87260085 0.18769209106341203 0.24550604649933191

5it [28:42, 344.56s/it]

3082.0151 0.33049836239959746 4.2706084 1.0071052 0.19419720057600276 0.283133860092902
NAM

0it [00:00, ?it/s]

129/129 [==============================] - 1s 4ms/step

1it [08:27, 507.48s/it]

4199.404940229941 0.23327302918470158 0.020151675 0.13554537 0.1502888919264386 0.34558486951220446
129/129 [==============================] - 1s 3ms/step

2it [15:22, 453.29s/it]

4325.414021088569 0.2334194635639742 0.019406423 0.13312757 0.15167148657231763 0.3460390321560317
129/129 [==============================] - 1s 3ms/step

3it [16:41, 282.22s/it]

4342.640883903087 0.2613863618162813 0.036946163 0.18064809 0.15601333135125744 0.3601232726570846
129/129 [==============================] - 1s 4ms/step

4it [17:42, 194.82s/it]

4443.527462571309 0.32393263065756384 0.032000646 0.16882682 0.3167864946305671 0.4496698322679172
129/129 [==============================] - 1s 3ms/step

5it [25:43, 308.68s/it]

4266.326168339731 0.23690088901843645 0.027439132 0.15698445 0.15488003600973302 0.34717884862062054

XGBOOST

1it [00:05,  5.00s/it]

4052.002282623943 0.16471670648889097 0.0061814114 0.07661432 0.05952546537524033 0.26998467335505905

2it [00:06,  3.23s/it]

4189.6115525061405 0.16502010599611122 0.005670011 0.07345599 0.060997845903113114 0.27429331456760325

3it [00:08,  2.65s/it]

4164.294758760327 0.17369161769631847 0.0062002316 0.07672793 0.06785112777391153 0.27149459477112897

4it [00:10,  2.37s/it]

4120.205219552795 0.1679235304721797 0.0068326965 0.08044398 0.07372111132017245 0.26997745404618895

5it [00:12,  2.57s/it]

4114.720840445743 0.1636005855276625 0.0066545606 0.079416335 0.06503554487972113 0.2691788189907882
EBM

1it [01:05, 65.60s/it]

4089.3416768109473 0.1820830932198055 0.011701107 0.10440791 0.09710738130300489 0.29391932811393073

2it [02:09, 64.44s/it]

4219.586727387703 0.1801176423390444 0.009406522 0.09395051 0.08933356243138613 0.2972769459389324

3it [03:13, 64.45s/it]

4198.432226780799 0.1904773848138407 0.010825045 0.10055685 0.09062481675260756 0.2998867287589843

4it [04:15, 63.36s/it]

4164.404202283658 0.18925037597645464 0.010791011 0.100403965 0.10161788438524416 0.2984717599831944

5it [05:14, 62.91s/it]

4167.385331707406 0.18906356394862237 0.012999356 0.10984135 0.09825674218529894 0.2959715094659984
NODEGAM

0it [00:00, ?it/s]

Normalize y. mean = 0.004887163460518012, std = 1.005165800066195

/usr/local/lib/python3.10/dist-packages/qhoptim/pyt/qhadam.py:133: UserWarning: This overload of add_ is deprecated:
	add_(Number alpha, Tensor other)
Consider using one of the following signatures instead:
	add_(Tensor other, *, Number alpha) (Triggered internally at ../torch/csrc/utils/python_arg_parser.cpp:1485.)
  exp_avg.mul_(beta1_adj).add_(1.0 - beta1_adj, d_p)
1it [05:23, 323.79s/it]

4212.972605360537 0.2395832900987766 0.026890278 0.15548807 0.14818161816469766 0.3513143158503448
Normalize y. mean = -0.007064393263778371, std = 0.9951682165725841

2it [09:47, 288.52s/it]

4323.8956932309775 0.23265473041058882 0.027346939 0.15673423 0.14413816977087038 0.34445166529180904
Normalize y. mean = -0.0055846589782885085, std = 0.9983359894293016

3it [13:23, 255.30s/it]

4322.0336856780705 0.25125357662722475 0.030986339 0.16627884 0.14866840070116216 0.35418573820390437
Normalize y. mean = 0.004214591263286725, std = 1.0007367574723751

4it [18:20, 271.82s/it]

4272.744013408477 0.2415263848586197 0.025359944 0.15122485 0.15492750304510414 0.3479792342846783
Normalize y. mean = 0.0035471653887682465, std = 1.000498802604787

5it [21:41, 260.20s/it]

4291.536141844756 0.24908976611518852 0.030176014 0.16420984 0.15461126230500694 0.3539091980771031

In [8]:
results = results.astype({"Likelihood": float})
results = results.astype({"MSE": float})
results = results.astype({"CRSP": float})
results = results.astype({"Wasserstein": float})
results = results.astype({"KL": float})
results = results.astype({"SKL": float})
results.groupby("Model").mean()

          Likelihood       MSE         KL       SKL  Wasserstein      CRSP
Model
DDNN     8433.329000  0.175189  27.492737  1.354904     0.066082  0.193388
EBM      4167.830033  0.186198   0.011145  0.101832     0.095388  0.297105
MLP      4143.314654  0.174314   0.007763  0.085202     0.066563  0.263996
NA2MLSS  2891.896820  0.307356   3.513043  0.934860     0.198360  0.272619
NAM      4315.462695  0.257782   0.027189  0.155026     0.185928  0.369719
NAMLSS   3684.621860  0.343098   5.232384  0.996731     0.207965  0.286763
NODEGAM  4284.636428  0.242822   0.028152  0.158787     0.150105  0.350368
XGBOOST  4128.166931  0.166991   0.006308  0.077332     0.065426  0.270986

In [9]:
results.groupby("Model").std()

           Likelihood       MSE        KL       SKL  Wasserstein      CRSP
Model
DDNN     14671.736424  0.004764  4.204087  0.023955     0.008340  0.002025
EBM         49.466165  0.004737  0.001323  0.005843     0.005228  0.002295
MLP         51.054598  0.005814  0.001686  0.008745     0.010850  0.003710
NA2MLSS    750.026887  0.042653  0.950250  0.080497     0.012448  0.018810
NAM         90.997346  0.038792  0.007558  0.020675     0.073189  0.045098
NAMLSS     408.647542  0.015018  0.363226  0.023760     0.008960  0.005965
NODEGAM     45.454878  0.007515  0.002354  0.006281     0.004608  0.004145
XGBOOST     52.739694  0.004072  0.000456  0.002736     0.005685  0.002030